[features]
seeds = false
skip-lint = false

[programs.localnet]
dilemma_arena = "7F1tQjn9AKT4S5PB2Kifr8Ck9ZRE77y83HoDUBXRNox1"

[programs.devnet]
dilemma_arena = "7F1tQjn9AKT4S5PB2Kifr8Ck9ZRE77y83HoDUBXRNox1"

[programs.mainnet]
dilemma_arena = "7F1tQjn9AKT4S5PB2Kifr8Ck9ZRE77y83HoDUBXRNox1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/dilemma-arena"]
