[network]
rpc_url = "https://api.devnet.solana.com"
program_id = "89Pm5Qy61r1K8dLY1Z1fsJLu3PBN5tTLfZFoEAhejDYa"

[wallets]
admin = "~/.config/solana/id.json"
operator = "~/.config/solana/operator.json"

[web]
url = "https://prisoners-arena.com"

[defaults]
stake = 50000000
min_participants = 2
max_participants = 100
registration_duration = 60
matches_per_player = 6
house_fee_bps = 0
reveal_duration = 60
